version: '3.8'
services:
  backend:
    build: ./../backend
    ports:
      - "8000:8000"
    env_file:
      - ./../backend/.env.example
    volumes:
      - ./../backend/app:/app/app
      - ./../backend/chroma:/app/chroma
      - ./../backend/data:/app/data
  nginx:
    image: nginx:alpine
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/default.conf:ro
      - ./../backend/data/audio:/var/www/audio:ro
    command: ["nginx", "-g", "daemon off;"]
