version: '3.8'
name: rag
services:
  backend:
    build: ./../backend
    ports:
      - "8000:8000"
    env_file:
      - ./../backend/.env.example
    volumes:
      - ./../backend/app:/app/app
      - ./../backend/chroma:/app/chroma
      - ./../backend/data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
  caddy:
    image: caddy:2-alpine
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./../backend/data/audio:/var/www/audio:ro
    restart: unless-stopped
