version: '3.8'
services:
  backend:
    build: ./../backend
    image: rm-rag-backend:latest
    restart: unless-stopped
    env_file:
      - ./../backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./../backend/chroma:/app/chroma
      - ./../backend/data:/app/data

  nginx:
    image: nginx:alpine
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./../backend/data/audio:/var/www/audio:ro
    command: ["/bin/sh", "-c", "envsubst < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;' "]
