version: '3.8'
name: rag
services:
  backend:
    image: ${IMAGE:-ghcr.io/reachmagnets-hue/crm-backend:latest}
    env_file:
      - ./.env
    volumes:
      - /opt/rag-data:/app/data
      - /opt/rag-chroma:/app/chroma
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/default.conf:ro
      - /opt/rag-data/audio:/var/www/audio:ro
    restart: unless-stopped
