name: ci

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-and-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: monorepo/backend
          file: monorepo/backend/Dockerfile
          tags: local/crm-backend:ci
          push: false
          load: true

      - name: Run container
        run: |
          docker run -d --rm -p 8000:8000 --name crm-backend-ci local/crm-backend:ci

      - name: Smoke test /health
        run: |
          for i in $(seq 1 20); do
            if curl -fsS http://127.0.0.1:8000/health | grep -q '"ok"'; then
              echo "Health OK"; exit 0; fi
            echo "Waiting for service... ($i)"; sleep 1;
          done
          echo "Health check failed" >&2
          docker logs crm-backend-ci || true
          exit 1

      - name: Stop container
        if: always()
        run: |
          docker stop crm-backend-ci || true
