name: build-and-deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/reachmagnets-hue/crm-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: monorepo/backend
          file: monorepo/backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Copy compose and nginx to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: |
            monorepo/infra/docker-compose.prod.yml
            monorepo/infra/nginx.conf.template
          target: ${{ secrets.VPS_APP_PATH }}

      - name: Write prod .env on VPS (if provided)
        uses: appleboy/ssh-action@v1.2.0
        env:
          PROD_ENV: ${{ secrets.PROD_ENV }}
          APP_PATH: ${{ secrets.VPS_APP_PATH }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            sudo mkdir -p /opt/rag-data /opt/rag-chroma
            sudo chown -R $(whoami):$(whoami) /opt/rag-data /opt/rag-chroma
            mkdir -p "$APP_PATH"
            if [ -n "${PROD_ENV}" ]; then echo "$PROD_ENV" | base64 -d > "$APP_PATH/.env"; fi

      - name: Deploy via docker compose
        uses: appleboy/ssh-action@v1.2.0
        env:
          APP_PATH: ${{ secrets.VPS_APP_PATH }}
          IMAGE: ghcr.io/reachmagnets-hue/crm-backend:latest
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            cd "$APP_PATH"
            docker compose -f docker-compose.prod.yml pull
            IMAGE=$IMAGE docker compose -f docker-compose.prod.yml up -d
