name: build-and-deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/reachmagnets-hue/crm-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: monorepo/backend
          file: monorepo/backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Copy compose and nginx to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: |
            monorepo/infra/docker-compose.prod.yml
            monorepo/infra/nginx.conf.template
          target: ${{ secrets.VPS_APP_PATH }}

      - name: Write prod .env on VPS (if provided)
        uses: appleboy/ssh-action@v1.2.0
        env:
          PROD_ENV: ${{ secrets.PROD_ENV }}
          APP_PATH: ${{ secrets.VPS_APP_PATH }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            sudo mkdir -p /opt/rag-data /opt/rag-chroma
            sudo chown -R $(whoami):$(whoami) /opt/rag-data /opt/rag-chroma
            mkdir -p "$APP_PATH"
            if [ -n "${PROD_ENV}" ]; then echo "$PROD_ENV" | base64 -d > "$APP_PATH/.env"; fi

      - name: Log in to GHCR on VPS (required if image is private)
        uses: appleboy/ssh-action@v1.2.0
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: false
          script: |
            set -euo pipefail
            if [ -n "${GHCR_USERNAME:-}" ] && [ -n "${GHCR_PAT:-}" ]; then
              echo "$GHCR_PAT" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin || true
            else
              echo "Skipping GHCR login on VPS (no credentials provided). Ensure package is public or set GHCR_USERNAME and GHCR_PAT secrets." >&2
            fi

      - name: Deploy via docker compose
        uses: appleboy/ssh-action@v1.2.0
        env:
          APP_PATH: ${{ secrets.VPS_APP_PATH }}
          IMAGE: ghcr.io/reachmagnets-hue/crm-backend:latest
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            cd "$APP_PATH"
            docker compose -f docker-compose.prod.yml pull
            IMAGE=$IMAGE docker compose -f docker-compose.prod.yml up -d

      - name: Smoke test health endpoint
        uses: appleboy/ssh-action@v1.2.0
        env:
          APP_PATH: ${{ secrets.VPS_APP_PATH }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            # Wait for nginx/back-end to respond on /health
            for i in $(seq 1 20); do
              if curl -fsS http://localhost/health | grep -q '"ok":'; then
                echo "Health check passed"; exit 0;
              fi
              echo "Waiting for service... ($i)"; sleep 3;
            done
            echo "Health check failed, showing recent backend logs" >&2
            cd "$APP_PATH" && docker compose -f docker-compose.prod.yml logs --no-color --tail=200 backend || true
            exit 1
